

-- hello to you if u were able to get here
-- u silly goober
-- we added key systems to directly scripts btw
-- dont bother yourself :3



game.StarterGui:SetCore("SendNotification", {
    Title = "GG HUB",
    Text = "Might be laggy, wait a minute pls",
    Duration = 5
})


loadstring(game:HttpGet("https://raw.githubusercontent.com/Farx11122/Others/refs/heads/main/WS", true))()

local gameId = game.PlaceId  

-- Main Games  
local popItGameId                = 7346416636  
local petsGameId                 = 7903991471  
local carsGameId                 = 8216162783  
local toysGameId                 = 7503115095  
local mm2GameId                  = 142823291  
local emhaGameId                 = 7711635737  
local hideordieGameId            = 18799085098  
local princesstycGameId          = 3804735158  
local SupermarketsimGameId       = 96462622512177  
local beacentipedeGameId         = 18209375211  
local SurvivenightmareGameId     = 16896041188  
local BloodOfPunchGameId         = 86230775293861  
local makevideosGameId           = 120444489340872  
local spindownGameId             = 17863864204  
local vcLobbySpindownGameId      = 123843608435731  
local protecthouseGameId         = 115286378269814  
local fishitGameId               = 121864768012064  
local stealbrainrotGameId        = 89735961041679  
local lastLetterGameId           = 129866685202296  
local myFishingBrainrotGameId    = 113489516847696  
local escapeTsunamiGameId        = 131623223084840  
local swingobbyGameId            = 114640202062357  
local breakEggGameId             = 119271610514030  
local parkourBrainrotGameId      = 75034791252172  

-- Recently Games  
local SurviveZombieArenaId       = 98927955463992  
local SlimeRNGGameId             = 92416421522960  
local BbqitGameId                = 88518003689791  


-- GAME CHECKS  

if gameId == popItGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/DupeSsv2"))()

elseif gameId == petsGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/PetTrading"))()

elseif gameId == carsGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/CarsTrading"))()

elseif gameId == toysGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/toys"))()

elseif gameId == mm2GameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Murderer%20Myster%202"))()

elseif gameId == emhaGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/EmergencyHamburg_GGHUG"))()

elseif gameId == hideordieGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Hideordie"))()

elseif gameId == princesstycGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/PrincessTycoon"))()

elseif gameId == SupermarketsimGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Supermarketsim"))()

elseif gameId == beacentipedeGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/BeAcentipede"))()

elseif gameId == SurvivenightmareGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Survive_nightmare_XChristianXsj"))()

elseif gameId == BloodOfPunchGameId
    or gameId == 125067579372958
    or gameId == 119696268487200
    or gameId == 137535317402998
    or gameId == 78606308971979
    or gameId == 114268110379653 then

    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Punch_Of_Blood"))()

elseif gameId == makevideosGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/make%20videos%20to%20become%20rich%20and%20famous"))()

elseif gameId == spindownGameId or gameId == vcLobbySpindownGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Spindown"))()

elseif gameId == protecthouseGameId
    or gameId == 129028588391526 then

    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Protecthousefromzombs"))()

elseif gameId == fishitGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Fish_it"))()

elseif gameId == stealbrainrotGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/PullaBrainrot"))()

elseif gameId == lastLetterGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/Last%20letter"))()

elseif gameId == myFishingBrainrotGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/MyFishinhBrainrot"))()

elseif gameId == escapeTsunamiGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/EscapeTsunamiBrainrot"))()

elseif gameId == swingobbyGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/SwingObbyForBrainrot"))()

elseif gameId == breakEggGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/BreakaBrainrotEgg"))()

elseif gameId == parkourBrainrotGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/ParkourForBrainrots"))()

elseif gameId == SurviveZombieArenaId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/SurviveZombieArena"))()

elseif gameId == SlimeRNGGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/SlimeRng"))()

elseif gameId == BbqitGameId then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/fsh4/MyHub/main/BBQTycoon.lua"))()

else
    warn("GG Hub does not support this game")

    game.StarterGui:SetCore("SendNotification", {
        Title = "GG HUB",
        Text = "NOT SUPPORTED GAME",
        Duration = 50
    })
end
